###
POST http://localhost:3000/api/posts/add
Content-Type: application/json

{
    "titulo": "PruebaDomingo",
    "img": "www.google.cl",
    "descripcion": "prueba descripcion",
    "likes": 2
}


###
GET  http://localhost:3000/api/posts/getPosts
Content-Type: 'aplication/json'